### ISSUE TITLE
TODO 12/30

### ISSUE THREAD

**Issue by adebruine** [northbynorthwestern/2018-year-in-media#11]
- [ ] - fix header on article pages (to match front, also doesn't adjust to changing window size)
- [ ] - change font on article pages? maybe larger? justified on both sides? it's just kinda ugly
- [x] - Coco page: messed up image
- [x] - Chester Bennington page: youtube vid not centered
- [x] - Fiona the Hippo page: bottom paragraph messed up
- [x] - Trans military ban page: missing author (prob issue w key)
- [x] - Trump page: missing article??

**Comment by adebruine** [comment]
oops dates are hard. thanks dude!!!
